Repository jointwt/twtxt, pull requests merged in 2020-08, with the labels that each got.

#68 Update and improve handling to include conventional (re ...)
  models.go
  templates/timeline.html
  tweets.go
  utils.go
Labels: dependencies

#69 Add Media Upload Support
  .gitignore
  cmd/twtd/main.go
  config.go
  context.go
  data/media/bPZoUmkwe6aXjCrMAEyHLK.png
  go.mod
  go.sum
  handlers.go
  options.go
  server.go
  static/css/twtxt.css
  static/js/twtxt.js
  templates/timeline.html
  utils.go
Labels: dependencies

#66 Add a basic APIv1 set of endpoints
  api.go
  cmd/twtd/main.go
  config.go
  handlers.go
  models.go
  options.go
  passwords/passwords.go
  passwords/scrypt_passwords.go
  router.go
  router_test.go
  server.go
Labels: help wanted, tests

#76 Restructure the source so the top-level is a bit less noisey
  .gitignore
  Makefile
  cmd/twtd/main.go
  doc.go
  internal/api.go
  internal/bitcask_store.go
  internal/cache.go
  internal/config.go
  internal/context.go
  internal/feedsources.go
  internal/handlers.go
  internal/jobs.go
  internal/models.go
  internal/options.go
  internal/profile.go
  internal/router.go
  internal/router_test.go
  internal/server.go
  internal/static/css/iconicss.min.css
  internal/static/css/pico.css
  internal/static/css/theme-switcher.css
  internal/static/css/twtxt.css
  internal/static/favicon.ico
  internal/static/img/.gitkeep
  internal/static/js/.gitkeep
  internal/static/js/theme-switcher.js
  internal/static/js/twtxt.js
  internal/static/js/umbrella.min.js
  internal/store.go
  internal/templates.go
  internal/templates/401.html
  internal/templates/404.html
  internal/templates/_partials.html
  internal/templates/about.html
  internal/templates/base.html
  internal/templates/error.html
  internal/templates/feeds.html
  internal/templates/follow.html
  internal/templates/followers.html
  internal/templates/help.html
  internal/templates/import.html
  internal/templates/login.html
  internal/templates/newPassword.html
  internal/templates/privacy.html
  internal/templates/profile.html
  internal/templates/register.html
  internal/templates/resetPassword.html
  internal/templates/settings.html
  internal/templates/support.html
  internal/templates/timeline.html
  internal/tweets.go
  internal/utils.go
  internal/version.go
Labels: tests

#88 Add support for editing and deleting your last Twt
  go.mod
  go.sum
  internal/context.go
  internal/handlers.go
  internal/models.go
  internal/server.go
  internal/static/js/serialize.min.js
  internal/static/js/twix.min.js
  internal/static/js/twtxt.js
  internal/templates/_partials.html
  internal/templates/base.html
  internal/tweets.go
Labels: dependencies

#95 Add support for syndication formats (RSS, Atom, JSON Feed)
  go.mod
  go.sum
  internal/context.go
  internal/handlers.go
  internal/server.go
  internal/templates/base.html
Labels: dependencies

#108 Add a basic CLI client with login and post commands
  .goreleaser.yml
  Dockerfile.twt
  Dockerfile.twtd
  Makefile
  client/client.go
  client/config.go
  client/options.go
  cmd/twt/login.go
  cmd/twt/main.go
  cmd/twt/post.go
  cmd/twt/root.go
  cmd/twtd/main.go
  go.mod
  go.sum
  internal/api.go
  internal/bitcask_store.go
  internal/cache.go
  internal/config.go
  internal/context.go
  internal/feedsources.go
  internal/handlers.go
  internal/jobs.go
  internal/models.go
  internal/options.go
  internal/profile.go
  internal/router.go
  internal/server.go
  internal/store.go
  internal/templates.go
  internal/twt.go
  internal/utils.go
  types/api.go
  types/twt.go
  version.go
Labels: dependencies, tests

#113 Add support for configurable img whitelist
  cmd/twtd/main.go
  go.mod
  go.sum
  internal/config.go
  internal/options.go
  internal/utils.go
Labels: dependencies

#120 Contact Form Added With Captcha Support.
  go.mod
  go.sum
  internal/handlers.go
  internal/server.go
  internal/static/css/twtxt.css
  internal/templates/support.html
Labels: dependencies

#122 Add WebMentions and basic IndieWeb µFormats v2 support (h-card, h-entry)
  .github/workflows/go.yml
  go.mod
  go.sum
  internal/api.go
  internal/context.go
  internal/handlers.go
  internal/jobs.go
  internal/models.go
  internal/server.go
  internal/templates.go
  internal/templates/_partials.html
  internal/templates/base.html
  internal/templates/externalProfile.html
  internal/templates/permalink.html
  internal/templates/profile.html
  internal/templates/timeline.html
  internal/twt.go
  internal/utils.go
  types/twt.go
Labels: dependencies

#130 Add support for WebP image format
  go.mod
  go.sum
  internal/api.go
  internal/cache.go
  internal/context.go
  internal/handlers.go
  internal/jobs.go
  internal/models.go
  internal/server.go
  internal/templates/_partials.html
  internal/templates/base.html
  internal/templates/profile.html
  internal/templates/settings.html
  internal/twt.go
  internal/utils.go
Labels: dependencies

#138 Add a DiskArchver that implements a Cache TTL
  .gitignore
  cmd/twtd/main.go
  data/archive/.gitkeep
  go.mod
  go.sum
  internal/api.go
  internal/archive.go
  internal/cache.go
  internal/config.go
  internal/handlers.go
  internal/init.go
  internal/jobs.go
  internal/options.go
  internal/server.go
  internal/twt.go
  types/twt.go
Labels: dependencies

#147 Replace postas with post_as
  docs/_posts/2020-08-05-api.md
Labels: documentation

#152 Add support for long-form posts (blog posts) with integrated twt(s).
  .gitignore
  data/blogs/.gitkeep
  internal/blog.go
  internal/blog_handlers.go
  internal/server.go
  internal/static/css/03-icons.css
  internal/static/css/twtxt.min.css
  internal/static/js/99-twtxt.js
  internal/static/js/twtxt.min.js
  internal/templates/_partials.html
  internal/templates/base.html
  internal/templates/blog.html
Labels: documentation

#156 Add unit tests for types.Feed
  Makefile
  go.mod
  internal/session/sid_test.go
  types/feed_test.go
Labels: tests

#157 Add unit tests for types.Twt.Subject() and fix the regex
  types/twt_test.go
Labels: tests
