Repository jointwt/twtxt, pull requests merged in 2020-09, with the labels that each got.

#160 Add /blogs view to display all twt blog posts for an author
  go.mod
  go.sum
  internal/blog.go
  internal/blog_handlers.go
  internal/context.go
  internal/handlers.go
  internal/models.go
  internal/profile.go
  internal/robots.go
  internal/server.go
  internal/session_store.go
  internal/templates/_partials.html
  internal/templates/blogs.html
  internal/utils.go
Labels: dependencies

#161 Add integrated support for conversations
  internal/conversation_handler.go
  internal/handlers.go
  internal/models.go
  internal/server.go
  internal/static/css/03-icons.css
  internal/static/css/twtxt.min.css
  internal/static/js/99-twtxt.js
  internal/static/js/twtxt.min.js
  internal/templates.go
  internal/templates/_partials.html
  internal/templates/blog.html
  internal/templates/conversation.html
  internal/templates/externalProfile.html
  internal/templates/profile.html
  internal/templates/timeline.html
  internal/twt.go
  internal/utils.go
  types/twt.go
  types/twt_test.go
Labels: tests

#176 Fix ExpandTags() function so links to Github issue comments work and add unit tess
  internal/twt.go
  internal/twt_test.go
Labels: tests

#193 Add support for persisting Title and Text in Twts and Twt Blogs to local storage
  go.mod
  go.sum
  internal/static/js/99-twtxt.js
  internal/static/js/twtxt.min.js
Labels: enhancement

#170 Add support for managing a pod's configuration as a pod owner
  .gitignore
  cmd/twtd/main.go
  go.mod
  go.sum
  internal/config.go
  internal/context.go
  internal/handlers.go
  internal/options.go
  internal/server.go
  internal/static/js/twtxt.min.js
  internal/templates.go
  internal/templates/manage.html
  internal/templates/settings.html
  internal/utils.go
Labels: dependencies
